### ISSUE TITLE
You should use __dirname or require-dir

### ISSUE THREAD

**Issue by kodypeterson** [sean3z/wol-ladder#3]
https://github.com/sean3z/wol-ladder/blob/develop/src/app.js#L19

Using require(./SomeFile) will work just fine as long as node is ran in the root directory of the project. But, if your run the project from outside the root you will get errors.

To solve this, use __dirname or https://www.npmjs.com/package/require-dir

**Comment by sean3z** [comment]
Fixed in 9fda0d4

Good explanation as to why __dirname is better in some cases :)
http://stackoverflow.com/a/18283508

**Comment by kodypeterson** [comment]
Yep! Much better :) and I prefer __dirname as well
