### ISSUE TITLE
We all love colors, but not really

### ISSUE THREAD

**Issue by kodypeterson** [sean3z/wol-ladder#7]
https://github.com/sean3z/wol-ladder/blob/develop/src/app.js#L73

Use https://www.npmjs.com/package/colors instead of hard-coding the color, this allows for cleaner code and full support in all operating systems and environments

**Comment by sean3z** [comment]
a2a54ff Decided to remove the color anyway since the app will ultimately be wrapped in pm2. Leaving the listen confirmation in for now for development
